AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  MembershipSrcObjectKey:
    Type: String
    Description: S3 object key of the membership lambda code .zip file
  ApplicationSrcObjectKey:
    Type: String
    Description: S3 object key of the application lambda code .zip file
  SwaggerObjectKey:
    Type: String
    Description: S3 object key of the membership api swagger file
  Branch:
    Type: String
    Default: "main"
    Description: Environment lambda is deployed in - Test or Prod.

Resources:
  MembershipApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub membership-api-handler-${Branch}
      Handler: app.handler
      Runtime: python3.8
      Role: !GetAtt MembershipApiLambdaRole.Arn
      CodeUri:
        Bucket: {lambda_bucket}
        Key: !Ref MembershipSrcObjectKey
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BRANCH: !Ref Branch
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  ApplicationApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub application-api-handler-${Branch}
      Handler: app.handler
      Runtime: python3.8
      Role: !GetAtt MembershipApiLambdaRole.Arn
      CodeUri:
        Bucket: {lambda_bucket}
        Key: !Ref ApplicationSrcObjectKey
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BRANCH: !Ref Branch
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  
  MembershipApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub Membership-Api-${Branch}
      StageName: !Ref Branch
      Auth:
        ApiKeyRequired: true
        AddApiKeyRequiredToCorsPreflight: false
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: MembershipApiAuthorization
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub 's3://{lambda_bucket}/${SwaggerObjectKey}'

  MembershipApiLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub MembershipApiLambdaRole-${Branch}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DatabaseCredentials
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!db-570bc63b-c275-489b-b7b0-7dd4c321f3af-0FQtiu"
        - PolicyName: ApplicationTablePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                Resource:
                  - !GetAtt ApplicationTable.Arn

  MembershipLambdaPermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt MembershipApiLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MembershipApiGateway}/*/*/*"

  ApplicationLambdaPermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ApplicationApiLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MembershipApiGateway}/*/*/*"
  
  ApplicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub applications-${Branch}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
