version: '3.4'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"

  application-api:
    image: application-api:local
    container_name: application-api
    ports:
      - "9002:8080"
    environment:
      BRANCH: 'local'
      AWS_ACCESS_KEY_ID: 'id'
      AWS_SECRET_ACCESS_KEY: 'key'
      AWS_SESSION_TOKEN: 'token'
      DYNAMO_ENDPOINT: 'http://dynamodb:8000'
    depends_on:
      - dynamodb
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'local_db'

  membership-api:
    image: membership-api:local
    container_name: membership-api
    ports:
      - "9001:8080"
    environment:
      BRANCH: 'local'
      DB_USER: 'postgres'
      DB_PASSWORD: 'password'
      DB_NAME: 'local_db'
      DB_ENDPOINT: 'postgres'
      DB_PORT: '5432'
    depends_on:
      - postgres

  proxy:
    image: openresty/openresty:alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - "9000:80"
    depends_on:
      - application-api
      - membership-api
